development:
  application:
    name:              KittyPad
    rss_title:         Application Name for RSS-Feeds
    title_prefix:      'HTML-Title-Prefix:'
    stylesheet_screen: forum
    stylesheet_print:  forum
    layout:            forum
    copyright:         KittyPad Inc. All rights reserved.
    copyright_url:     http://www.kittypad.com
    meta_keywords:  "education, educational, fun, games, kids, preschool, toddler, ipad, apple, app store, iphone, elementary school, math, english, music, drawing, kittypad, pad, apps, applications"
    meta_description:  "KittyPad's parents forum is a platform for parents to learn more about children's education through Ipad. Parents can discuss and share their experience in raising, educating and connecting with their children in KittyPad's parents forum. Besides, parents can find the best educational applications here."
    registration_from: 'noreply@kittypad.com'
    admin_notification_address: 'admin@kittypad.com'
    registration_from: 'test@kittypad.com'
    slogan:            'unfuzzy development (env=dev)'
    pivotal_tracker_project: 'http://www.pivotaltracker.com/projects/203457'
    twitter_name: '@Twitter'
    twitter_link: 'http://twitter.com/nickendell'
  constants:
    max_time_to_edit_new_comments: 2
    rss_feed_cache_time:           1.minute
    paginate_postings_per_page:    2
    paginate_episodes_per_page:    2
    num_postings_on_welcome_page:  2
    postings_on_homepage:          6
    sleep_in_delayed_jobs_worker:  10
    paginate_users_per_page:       2    
    rating_range:                  (1..5)
    paginate_ratings_per_page:     2
    paginate_blog_entries_per_page: 2
    delay_new_posting_notifications: 9
    sleep_in_delayed_jobs_worke:   5
    title_max_length: 30
    max_size_of_attachments_in_mb: 1
test:
  application:
    name:              TESTAPPLICATION
    rss_title:         TESTFEED
    title_prefix:      'iBoard.cc (test): '    
    stylesheet_screen: forum
    stylesheet_print:  forum
    layout:            forum
    copyright:         Andreas Altendorfer
    copyright_url:     http://altendorfer.at
    meta_description:  'Author: Andreas Altendorfer, iboard.cc, IT-Veteran, Developer, Musik Benzin und Kuchen'
    admin_notification_address: 'admin@your.domain'
    registration_from: 'test@application.tt'
    admin_notification_address: 'test@application.tt'
    registration_from: 'test@application.tt'
    slogan:            'unfuzzy development (env=test)'
    pivotal_tracker_project: 'http://www.pivotaltracker.com/projects/203457'
    github_project: 'http://github.com/iboard/CBA'
    twitter_name: '@Twitter'
    twitter_link: 'http://twitter.com/nickendell'    
  constants:
    max_time_to_edit_new_comments: 15    
    rss_feed_cache_time:           0
    paginate_postings_per_page:    6
    paginate_episodes_per_page:    6
    paginate_users_per_page:       6    
    num_postings_on_welcome_page:  6
    sleep_in_delayed_jobs_worker:  1
    postings_on_homepage:          6
    rating_range:                  (1..5)
    paginate_ratings_per_page:     20
    paginate_blog_entries_per_page: 20
    delay_new_posting_notifications: 9
    sleep_in_delayed_jobs_worke:   1
    title_max_length: 30
    max_size_of_attachments_in_mb: 1
staging:
  application:
    name:              KittyPad.com

    title_prefix:      'iBoard.cc: '
    stylesheet_screen: application
    stylesheet_print:  application
    layout:            application
    copyright:         © 2011 KittyPad Inc. All rights reserved.
    copyright_url:     http://kittypad.com
    meta_description:  'Author: Andreas Altendorfer, iboard.cc, IT-Veteran, Developer, Musik Benzin und Kuchen'
    registration_from: 'noreply@your.site'
    admin_notification_address: 'admin@your.domain'
    registration_from: 'test@application.tt'
    slogan:            'unfuzzy development that makes fun'
    pivotal_tracker_project: 'http://www.pivotaltracker.com/projects/203457'

    twitter_name: '@Twitter'
    twitter_link: 'http://twitter.com/nickendell'    
  constants:
    max_time_to_edit_new_comments: 15    
    rss_feed_cache_time:           10.minutes
    paginate_postings_per_page:    6
    paginate_episodes_per_page:    6
    paginate_users_per_page:       6    
    num_postings_on_welcome_page:  6
    postings_on_homepage:          6
    sleep_in_delayed_jobs_worker:  60
    rating_range:                  (1..5)
    paginate_ratings_per_page:     20
    paginate_blog_entries_per_page: 20
    delay_new_posting_notifications: 900
    sleep_in_delayed_jobs_worke:   59
    title_max_length: 30
    max_size_of_attachments_in_mb: 1
production:
  application:
    name:              KittyPad.com

    title_prefix:      'kittypad.com: '
    stylesheet_screen: application
    stylesheet_print:  application
    layout:            application
    copyright:         © 2011 KittyPad Inc. All rights reserved.
    copyright_url:     http://kittypad.com
    meta_keywords:  "education, educational, fun, games, kids, preschool, toddler, ipad, apple, app store, iphone, elementary school, math, english, music, drawing, kittypad, pad, apps, applications"
    meta_description:  "KittyPad's parents forum is a platform for parents to learn more about children's education through Ipad. Parents can discuss and share their experience in raising, educating and connecting with their children in KittyPad's parents forum. Besides, parents can find the best educational applications here."
    registration_from: 'noreply@your.site'
    admin_notification_address: 'admin@your.domain'
    registration_from: 'test@application.tt'
    slogan:            'unfuzzy development that makes fun'
    pivotal_tracker_project: 'http://www.pivotaltracker.com/projects/203457'

    twitter_name: '@Twitter'
    twitter_link: 'http://twitter.com/nickendell'    
  constants:
    max_time_to_edit_new_comments: 15    
    rss_feed_cache_time:           10.minutes
    paginate_postings_per_page:    6
    paginate_episodes_per_page:    6
    paginate_users_per_page:       6    
    num_postings_on_welcome_page:  6
    postings_on_homepage:          6
    sleep_in_delayed_jobs_worker:  60
    rating_range:                  (1..5)
    paginate_ratings_per_page:     20
    paginate_blog_entries_per_page: 20
    delay_new_posting_notifications: 900
    sleep_in_delayed_jobs_worke:   59
    title_max_length: 30
    max_size_of_attachments_in_mb: 1

