development: &defaults
connection:
  :access_key_id: AAAAAA_your-key-here
  :secret_access_key: 4rpsi235js_your-secret-here
  :use_ssl: true
  # :persistent: true
  bucket: project-development
  max_file_size: 10485760
  acl: public-read

test:
  <<: *defaults
  bucket: project-development

staging:
  <<: *defaults
  bucket: project-staging

production:
  <<: *defaults
  # prefix is optional. This is where you would put your CloudFront Domain
  # Name or your CloudFront CNAME if you have one configured.
  prefix: "http://project.s3.mydomain.com"
  bucket: project